sudo: false
language: node_js
node_js:
    - "4.2"

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

script:
    - npm test
