dist: trusty
sudo: false
language: node_js
node_js:
    - "6.10.2"

branches:
    only:
        - master
        - dev

cache:
    directories:
        - node_modules

addons:
  chrome: stable

#before_install:
#  - # start your web application and listen on `localhost:3000`
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000

install:
    - npm install

script:
    - npm test
