dist: trusty
sudo: false
language: node_js
node_js:
    - "6.10.2"

addons:
  chrome: stable

branches:
    only:
        - master
        - dev

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮

install:
    - npm install

cache:
    directories:
        - node_modules

script:
    - npm test
