sudo: false
language: node_js
node_js:
    - "4.2"

branches:
    only:
        - master
        - dev
before_install:
    - npm install -g grunt-cli

install:
    - npm install

cache:
    directories:
        - node_modules

script:
    - npm test
